version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: "0e0ec578-3987-459d-b19b-8a187777dff5"
  endpoints: public
  env:
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
