version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 08e59b9f-804b-48b2-821f-b356433e3882
  endpoints: public
  env:
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
