version: 1.0
app:
  services:
    - crn: 'crn:v1:bluemix:public:mqcloud:us-east:a/26a5e866a11a5014f2eca2acab86f048:123019ac-5871-4f20-8e10-1207b38721fc::'
  #  - name: mq-service
  #    type: mqcloud
  instances:
    min: 1
    max: 1
  version: "298502d2-bda7-4200-9db6-6da526a2f0a0"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
