version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 40fbb540-18f3-4d49-9017-9ee92006e1ca
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
