version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 10f08b5f-3f1b-4629-a3c5-8e88be7f4c9b
  endpoints: public
  env:
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
